---
abstract: 'Interact with CLI of Avaya Networking products over any of Telnet, SSH or Serial port'
author:
  - 'Ludovico Stevens <lstevens@cpan.org>'
build_requires:
  IO::Interactive: 0
  Net::Telnet: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Control-CLI-AvayaData
provides:
  Control::CLI::AvayaData:
    file: lib/Control/CLI/AvayaData.pm
    version: 1.00
requires:
  Control::CLI: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
